//go:build darwin && cgo

#import <WebKit/WebKit.h>
#import <Cocoa/Cocoa.h>

// Go-exported callback functions (generated by cgo into _cgo_export.h).
#include "_cgo_export.h"

// ---------------------------------------------------------------------------
// Delegate context — receives WKWebView navigation events and forwards
// them to the Go-exported callback functions.
// ---------------------------------------------------------------------------
@interface WebViewContext : NSObject <WKNavigationDelegate, WKUIDelegate>
@end

@implementation WebViewContext

// -- WKNavigationDelegate ---------------------------------------------------

- (void)webView:(WKWebView *)webView
    didStartProvisionalNavigation:(WKNavigation *)navigation {
    const char* url = [[[webView URL] absoluteString] UTF8String];
    _go_nav_callback(0, (char*)(url ?: ""));
    _go_loading_callback(true);
}

- (void)webView:(WKWebView *)webView
    didFinishNavigation:(WKNavigation *)navigation {
    const char* url = [[[webView URL] absoluteString] UTF8String];
    _go_nav_callback(1, (char*)(url ?: ""));
    const char* title = [[webView title] UTF8String];
    _go_title_callback((char*)(title ?: ""));
    _go_loading_callback(false);
}

- (void)webView:(WKWebView *)webView
    didFailNavigation:(WKNavigation *)navigation
            withError:(NSError *)error {
    const char* url = [[[webView URL] absoluteString] UTF8String];
    _go_nav_callback(2, (char*)(url ?: ""));
    _go_loading_callback(false);
}

- (void)webView:(WKWebView *)webView
    didFailProvisionalNavigation:(WKNavigation *)navigation
                       withError:(NSError *)error {
    const char* url = [[[webView URL] absoluteString] UTF8String];
    _go_nav_callback(2, (char*)(url ?: ""));
    _go_loading_callback(false);
}

- (void)webView:(WKWebView *)webView
    didReceiveServerRedirectForProvisionalNavigation:(WKNavigation *)navigation {
    const char* url = [[[webView URL] absoluteString] UTF8String];
    _go_nav_callback(3, (char*)(url ?: ""));
}

// -- WKUIDelegate -----------------------------------------------------------

- (void)webView:(WKWebView *)webView
    runJavaScriptAlertPanelWithMessage:(NSString *)message
    initiatedByFrame:(WKFrameInfo *)frame
    completionHandler:(void (^)(void))completionHandler {
    NSAlert* alert = [[NSAlert alloc] init];
    [alert setMessageText:message];
    [alert addButtonWithTitle:@"OK"];
    [alert runModal];
    completionHandler();
}

@end

// ---------------------------------------------------------------------------
// C-callable API
// ---------------------------------------------------------------------------

WebViewRef wkwebview_create(int width, int height) {
    @autoreleasepool {
        if (NSApp == nil) {
            [NSApplication sharedApplication];
        }

        NSRect frame = NSMakeRect(0, 0, width, height);
        NSWindow* window = [[NSWindow alloc] initWithContentRect:frame
                                                      styleMask:NSWindowStyleMaskTitled |
                                                                NSWindowStyleMaskClosable |
                                                                NSWindowStyleMaskMiniaturizable |
                                                                NSWindowStyleMaskResizable
                                                        backing:NSBackingStoreBuffered
                                                          defer:NO];
        [window setTitle:@"Compatibility Mode"];

        WKWebViewConfiguration* config = [[WKWebViewConfiguration alloc] init];
        WKWebView* webView = [[WKWebView alloc] initWithFrame:frame
                                                configuration:config];
        [webView setAutoresizingMask:NSViewWidthSizable | NSViewHeightSizable];

        WebViewContext* ctx = [[WebViewContext alloc] init];
        webView.navigationDelegate = ctx;
        webView.UIDelegate = ctx;

        [window setContentView:webView];
        [window makeKeyAndOrderFront:nil];
        [NSApp activateIgnoringOtherApps:YES];

        // Retain so the caller's WebViewRef stays valid.
        CFRetain((__bridge CFTypeRef)webView);
        CFRetain((__bridge CFTypeRef)window);

        return (__bridge_retained void*)webView;
    }
}

void wkwebview_destroy(WebViewRef wv) {
    if (!wv) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge_transfer WKWebView*)wv;
        NSWindow* window = [webView window];
        webView.navigationDelegate = nil;
        webView.UIDelegate = nil;
        [window orderOut:nil];
        [window close];
    }
}

void wkwebview_navigate(WebViewRef wv, const char* url) {
    if (!wv || !url) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        NSString* nsURL = [NSString stringWithUTF8String:url];
        NSURLRequest* req = [NSURLRequest requestWithURL:[NSURL URLWithString:nsURL]];
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView loadRequest:req];
        });
    }
}

void wkwebview_stop(WebViewRef wv) {
    if (!wv) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView stopLoading];
        });
    }
}

void wkwebview_reload(WebViewRef wv) {
    if (!wv) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView reload];
        });
    }
}

void wkwebview_go_back(WebViewRef wv) {
    if (!wv) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView goBack];
        });
    }
}

void wkwebview_go_forward(WebViewRef wv) {
    if (!wv) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView goForward];
        });
    }
}

bool wkwebview_can_go_back(WebViewRef wv) {
    if (!wv) return false;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        return (bool)[webView canGoBack];
    }
}

bool wkwebview_can_go_forward(WebViewRef wv) {
    if (!wv) return false;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        return (bool)[webView canGoForward];
    }
}

void wkwebview_load_html(WebViewRef wv, const char* html, const char* base_url) {
    if (!wv || !html) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        NSString* nsHTML = [NSString stringWithUTF8String:html];
        NSString* nsBase = base_url ? [NSString stringWithUTF8String:base_url] : nil;
        NSURL* baseURL = nsBase ? [NSURL URLWithString:nsBase] : nil;
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView loadHTMLString:nsHTML baseURL:baseURL];
        });
    }
}

void wkwebview_evaluate_js(WebViewRef wv, const char* script, int ctx_id) {
    if (!wv || !script) return;
    @autoreleasepool {
        WKWebView* webView = (__bridge WKWebView*)wv;
        NSString* nsScript = [NSString stringWithUTF8String:script];
        dispatch_async(dispatch_get_main_queue(), ^{
            [webView evaluateJavaScript:nsScript
                      completionHandler:^(id result, NSError* error) {
                NSString* resultStr;
                if (error) {
                    resultStr = [NSString stringWithFormat:@"{\"error\":\"%@\"}",
                                 [error localizedDescription]];
                } else if (result) {
                    resultStr = [NSString stringWithFormat:@"%@", result];
                } else {
                    resultStr = @"null";
                }
                _go_js_callback((char*)[resultStr UTF8String], ctx_id);
            }];
        });
    }
}

void wkwebview_set_private(WebViewRef wv, bool private) {
    // Full WKWebView privacy support requires creating an ephemeral
    // WKWebsiteDataStore at construction time, which cannot be toggled
    // after creation. For the prototype, this is a documented limitation.
    (void)wv;
    (void)private;
}

void wkwebview_show_devtools(WebViewRef wv) {
    (void)wv;
    [[NSUserDefaults standardUserDefaults]
        setBool:YES forKey:@"WebKitDeveloperExtras"];
}

void wkwebview_pump_events(WebViewRef wv) {
    @autoreleasepool {
        __weak WKWebView* weakWV = (__bridge WKWebView*)wv;
        while (weakWV != nil) {
            NSEvent* event = [NSApp nextEventMatchingMask:NSEventMaskAny
                                                untilDate:[NSDate distantFuture]
                                                   inMode:NSDefaultRunLoopMode
                                                  dequeue:YES];
            if (event) {
                [NSApp sendEvent:event];
            }
        }
    }
}
