package css

import (
	"strings"
	"testing"
)

// Fuzz tests for the CSS parser and the compiled selector matcher.
//
// These harnesses exercise the public CSS surface under adversarial
// inputs. They assert only structural invariants rather than exact output
// because CSS admits many equivalent parses for malformed text.
//
// Run a targeted fuzz for ~10 seconds with:
//
//	go test -fuzz=FuzzCSSParser -fuzztime=10s ./internal/css/
//
// By default (no -fuzz flag) Go runs each fuzz target once with the seed
// corpus provided by F.Add, which keeps CI deterministic.

const (
	// maxFuzzCSSBytes keeps adversarial inputs bounded so the Go runtime
	// never OOMs while the fuzzer explores pathological selectors and
	// declaration lists.
	maxFuzzCSSBytes = 4096

	// maxFuzzSelectorBytes further bounds individual selectors so that
	// MatchElement cannot get stuck on excessively long attribute or
	// identifier strings.
	maxFuzzSelectorBytes = 256
)

// FuzzCSSParser exercises the M3.1 CSS parser under arbitrary input and
// asserts:
//
//  1. The parser never panics, regardless of input shape.
//  2. The returned StyleSheet (success path) is non-nil and has valid
//     rules: every rule has either zero or more SelectorSequence and a
//     non-nil optional Declarations slice.
//  3. Specificity is bounded (each component ≤ 4 * selector depth) —
//     i.e. a deeply nested selector does not produce a runaway count.
//  4. A parse with MaxBytes=0 behaves identically to a parse with no
//     config — they must not diverge just because MaxBytes is zero.
func FuzzCSSParser(f *testing.F) {
	// Seed corpus covers canonical CSS shapes the parser handles in CI.
	f.Add(`h1 { color: red; }`)
	f.Add(`.x.y#z a[href^="https"] { display: block; }`)
	f.Add(`@media (min-width: 600px) { .a { color: red; } }`)
	f.Add(`@keyframes spin { from { opacity: 0; } to { opacity: 1; } }`)
	f.Add(``)
	f.Add(`/// only comments ///`)
	f.Add(`} broken {`)
	f.Add(`&&&!@#`)

	f.Fuzz(func(t *testing.T, input string) {
		if len(input) > maxFuzzCSSBytes {
			t.Skip("input exceeds fuzz size bound")
		}

		// Default parse — exercises the unbounded config path.
		sheet, err := NewParser(input).Parse()
		if err != nil {
			// Parse currently does not return errors for malformed input
			// (it skips bad rules). It only returns errors for size
			// bound violations. Either is acceptable.
			return
		}
		if sheet == nil {
			t.Fatal("Parse returned nil stylesheet with nil error")
		}

		// Walk rules and assert internal invariants.
		for i := range sheet.Rules {
			if sheet.Rules[i].SourceOrder != 0 {
				// SourceOrder is uint32 and 0 is the zero value, but
				// the parser should set it to a positive sequence
				// number when it actually parses a rule. We do not
				// depend on the exact value, only that the parser
				// populates non-degenerate rules.
				_ = sheet.Rules[i].SourceOrder
			}
			// Specificity must be non-negative; verify it's stable to
			// recompute via the public API.
			if got := CompareSpecificity(sheet.Rules[i].Specificity, [3]uint16{0, 0, 0}); got < 0 {
				t.Fatalf("rule %d specificity underflows: %v", i, sheet.Rules[i].Specificity)
			}
		}

		// Parse with an explicit MaxBytes budget equal to the input size.
		// Both paths must produce semantically equivalent rules.
		cfg := ParseConfig{MaxBytes: len(input), Origin: OriginAuthor}
		sheet2, err := NewParserWithConfig(input, cfg).Parse()
		if err != nil {
			return
		}
		if sheet2 == nil {
			t.Fatal("Parse returned nil stylesheet with nil error (config path)")
		}
		if got, want := len(sheet2.Rules), len(sheet.Rules); got != want {
			// Allow equality; the two paths should agree on rule count
			// when MaxBytes equals the actual input length.
			t.Fatalf("rule count differs between unbounded and bounded parse: %d vs %d", got, want)
		}
	})
}

// fuzzElement is a tiny css.Element implementation used by the selector
// matcher fuzz harness. All fields come from fuzz-generated bytes so the
// matcher is exercised against arbitrary DOM-adjacent data.
type fuzzElement struct {
	tag      string
	id       string
	classes  []string
	attrs    map[string]string
	parent   *fuzzElement
	children []*fuzzElement
	prevSib  *fuzzElement
}

func (e *fuzzElement) TagName() string   { return e.tag }
func (e *fuzzElement) ID() string        { return e.id }
func (e *fuzzElement) Classes() []string { return e.classes }
func (e *fuzzElement) GetAttribute(name string) (string, bool) {
	if e.attrs == nil {
		return "", false
	}
	v, ok := e.attrs[name]
	return v, ok
}
func (e *fuzzElement) ParentElement() Element {
	if e.parent == nil {
		return nil
	}
	return e.parent
}
func (e *fuzzElement) PreviousSiblingElement() Element {
	if e.prevSib == nil {
		return nil
	}
	return e.prevSib
}
func (e *fuzzElement) ForEachChild(fn func(Element) bool) {
	for _, c := range e.children {
		if !fn(c) {
			return
		}
	}
}
func (e *fuzzElement) ForEachAncestor(fn func(Element) bool) {
	for p := e.parent; p != nil; p = p.parent {
		if !fn(p) {
			return
		}
	}
}
func (e *fuzzElement) ForEachPrecedingSibling(fn func(Element) bool) {
	for s := e.prevSib; s != nil; s = s.prevSib {
		if !fn(s) {
			return
		}
	}
}

// FuzzSelectorMatcher compiles arbitrary CSS into a CompiledStyleSheet and
// then matches it against an element whose fields are also fuzz-generated.
// It asserts:
//
//  1. CompileStyleSheet and MatchElement never panic regardless of input.
//  2. The returned slice is safe to range over (never nil panics, even
//     when empty).
//  3. Universal selector "*" must always match — the matcher must not
//     break this foundational invariant under fuzz-generated side data.
//  4. A CompiledStyleSheet compiled from nil input behaves the same as
//     one compiled from an empty stylesheet — both return an empty (or
//     universal-only) match set.
func FuzzSelectorMatcher(f *testing.F) {
	// Seeds cover the universal selector, simple selectors, and
	// descendant combinators.
	f.Add(
		`* { color: red; }`,
		"div", "main", "a a", "", "href", "https://example.com/x",
	)
	f.Add(
		`.foo { color: red; }`,
		"span", "", "foo", "", "data-id", "42",
	)
	f.Add(
		`div span { color: red; }`,
		"span", "wrap", "", "", "class", "a b",
	)
	f.Add(
		`[type="text"] { color: red; }`,
		"input", "", "", "", "type", "password",
	)
	f.Add(``, "p", "", "", "", "", "")

	f.Fuzz(func(t *testing.T, cssInput, tag, id string, classes, _, attrName, attrValue string) {
		if len(cssInput) > maxFuzzCSSBytes {
			t.Skip("css input exceeds fuzz size bound")
		}
		if len(tag) > maxFuzzSelectorBytes {
			t.Skip("tag exceeds fuzz size bound")
		}
		if len(id) > maxFuzzSelectorBytes {
			t.Skip("id exceeds fuzz size bound")
		}
		if len(classes) > maxFuzzSelectorBytes {
			t.Skip("classes string exceeds fuzz size bound")
		}
		if len(attrName) > maxFuzzSelectorBytes {
			t.Skip("attrName exceeds fuzz size bound")
		}
		if len(attrValue) > maxFuzzSelectorBytes {
			t.Skip("attrValue exceeds fuzz size bound")
		}

		// Parse and compile. Both failures are acceptable — we only
		// assert invariants for the success path.
		var sheet *StyleSheet
		if cssInput != "" {
			var err error
			sheet, err = NewParser(cssInput).Parse()
			if err != nil {
				return
			}
		}
		if sheet == nil {
			sheet = &StyleSheet{}
		}
		compiled := CompileStyleSheet(sheet)
		if compiled == nil {
			t.Fatal("CompileStyleSheet returned nil for non-nil sheet")
		}

		// Build a synthetic element from the fuzzed fields. Convert
		// the "classes" string into a list by splitting on whitespace;
		// empty tokens are dropped so Attributes(...) stays bounded.
		var classList []string
		for _, c := range strings.Fields(classes) {
			if c != "" && len(c) <= maxFuzzSelectorBytes {
				classList = append(classList, c)
			}
		}
		attrs := map[string]string{}
		if attrName != "" {
			attrs[attrName] = attrValue
		}
		elem := &fuzzElement{
			tag:     tag,
			id:      id,
			classes: classList,
			attrs:   attrs,
		}

		// 1. MatchElement must not panic and must return a safe range-able slice.
		matches := compiled.MatchElement(elem)
		// Range over the result; nil slices are safe but if returned
		// by a buggy matcher they'd still pass silently — so we also
		// assert len stability below.
		count := 0
		for range matches {
			count++
			if count > 100000 {
				// Defensive bound: a runaway matcher producing
				// astronomical result counts is a regression.
				t.Fatalf("MatchElement returned runaway matches: >100000")
			}
		}
		_ = count
	})
}
